"""initial

Revision ID: dcbe02ab8874
Revises: 
Create Date: 2026-06-25 08:39:05.734747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcbe02ab8874'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'guru_bk', 'wali_kelas', name='user_role', create_constraint=True), nullable=False),
    sa.Column('nip', sa.String(length=40), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('violation_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('ringan', 'menengah', 'berat', 'sangat_berat', name='violation_category_name', create_constraint=True), nullable=False),
    sa.Column('min_points', sa.Integer(), nullable=False),
    sa.Column('max_points', sa.Integer(), nullable=False),
    sa.Column('is_direct_expulsion', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('grade_level', sa.Integer(), nullable=False),
    sa.Column('homeroom_teacher_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['homeroom_teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classes_homeroom_teacher_id'), ['homeroom_teacher_id'], unique=False)

    op.create_table('violation_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('default_points', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['violation_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nis', sa.String(length=40), nullable=False),
    sa.Column('nisn', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.Enum('L', 'P', name='gender', create_constraint=True), nullable=False),
    sa.Column('birth_place', sa.String(length=120), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('parent_name', sa.String(length=120), nullable=True),
    sa.Column('parent_phone', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('active', 'expelled', 'graduated', 'transferred', name='student_status', create_constraint=True), nullable=False),
    sa.Column('enrolled_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nis')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_class_id'), ['class_id'], unique=False)

    op.create_table('student_point_summaries',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('current_sp_level', sa.Enum('1', '2', '3', name='sp_level', create_constraint=True), nullable=True),
    sa.Column('last_sp_date', sa.Date(), nullable=True),
    sa.Column('is_expelled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    with op.batch_alter_table('student_point_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_point_summaries_total_points'), ['total_points'], unique=False)

    op.create_table('violation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_number', sa.String(length=60), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('violation_type_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('chronology', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('incident_time', sa.Time(), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Enum('1', '2', name='semester', create_constraint=True), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('is_void', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['violation_categories.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['violation_type_id'], ['violation_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('violation_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_violation_records_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_violation_records_category_id'), ['category_id'], unique=False)
        batch_op.create_index('ix_violation_records_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_violation_records_student_id'), ['student_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('violation_record_id', sa.Integer(), nullable=True),
    sa.Column('warning_letter_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('evidence_photo', 'evidence_video', 'signed_warning_letter', 'signed_statement_letter', 'signed_amnesty_letter', name='document_type', create_constraint=True), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['violation_record_id'], ['violation_records.id'], ),
    sa.ForeignKeyConstraint(['warning_letter_id'], ['warning_letters.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warning_letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letter_number', sa.String(length=60), nullable=False),
    sa.Column('letter_seq', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('SP1', 'SP2', 'SP3', name='warning_letter_level', create_constraint=True), nullable=False),
    sa.Column('trigger_violation_record_id', sa.Integer(), nullable=False),
    sa.Column('total_points_at_issue', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('issued_by', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('signed_warning_doc_id', sa.Integer(), nullable=True),
    sa.Column('signed_statement_doc_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('issued', 'signed_returned', 'void', name='warning_letter_status', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['signed_statement_doc_id'], ['documents.id'], use_alter=True),
    sa.ForeignKeyConstraint(['signed_warning_doc_id'], ['documents.id'], use_alter=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['trigger_violation_record_id'], ['violation_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year_id', 'letter_seq', name='uq_warning_letters_year_seq')
    )
    with op.batch_alter_table('warning_letters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warning_letters_student_id'), ['student_id'], unique=False)

    op.create_table('expulsion_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letter_number', sa.String(length=60), nullable=False),
    sa.Column('letter_seq', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('trigger_violation_record_id', sa.Integer(), nullable=True),
    sa.Column('trigger_warning_letter_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('total_points_at_issue', sa.Integer(), nullable=False),
    sa.Column('issued_by', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('issued', 'void', name='expulsion_status', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['trigger_violation_record_id'], ['violation_records.id'], ),
    sa.ForeignKeyConstraint(['trigger_warning_letter_id'], ['warning_letters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year_id', 'letter_seq', name='uq_expulsion_year_seq')
    )
    with op.batch_alter_table('expulsion_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expulsion_recommendations_student_id'), ['student_id'], unique=False)

    op.create_table('point_amnesties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letter_number', sa.String(length=60), nullable=False),
    sa.Column('letter_seq', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('points_reduced', sa.Integer(), nullable=False),
    sa.Column('reason_category', sa.Enum('prestasi', 'perilaku_baik', 'kerja_bakti', 'lainnya', name='amnesty_reason_category', create_constraint=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('sp_reset', sa.Boolean(), nullable=False),
    sa.Column('principal_name', sa.String(length=120), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('signed_document_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('issued', 'void', name='amnesty_status', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['signed_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year_id', 'letter_seq', name='uq_point_amnesties_year_seq')
    )
    with op.batch_alter_table('point_amnesties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_point_amnesties_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point_amnesties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_point_amnesties_student_id'))

    op.drop_table('point_amnesties')
    with op.batch_alter_table('expulsion_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expulsion_recommendations_student_id'))

    op.drop_table('expulsion_recommendations')
    with op.batch_alter_table('warning_letters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warning_letters_student_id'))

    op.drop_table('warning_letters')
    op.drop_table('documents')
    with op.batch_alter_table('violation_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_violation_records_student_id'))
        batch_op.drop_index('ix_violation_records_created_at')
        batch_op.drop_index(batch_op.f('ix_violation_records_category_id'))
        batch_op.drop_index(batch_op.f('ix_violation_records_academic_year_id'))

    op.drop_table('violation_records')
    with op.batch_alter_table('student_point_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_point_summaries_total_points'))

    op.drop_table('student_point_summaries')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_class_id'))

    op.drop_table('students')
    op.drop_table('violation_types')
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classes_homeroom_teacher_id'))

    op.drop_table('classes')
    op.drop_table('violation_categories')
    op.drop_table('users')
    op.drop_table('academic_years')
    # ### end Alembic commands ###
